// export function contractAddress (){
//     return "0xd9145CCE52D386f254917e481eB44e9943F39138"
// }

// export function contractABI(){
//     return '[{"inputs":[{"internalType":"string","name":"_fileHash","type":"string"},{"internalType":"string","name":"_ipfsHash","type":"string"}],"name":"addFile","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_uniqueId","type":"uint256"}],"name":"addUniqueId","outputs":[],"stateMutability":"nonpayable","type":"function"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"fileId","type":"uint256"},{"indexed":false,"internalType":"string","name":"fileHash","type":"string"},{"indexed":false,"internalType":"string","name":"ipfsHash","type":"string"}],"name":"FileAdded","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"uniqueId","type":"uint256"}],"name":"UniqueIdAdded","type":"event"},{"inputs":[],"name":"fileCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"files","outputs":[{"internalType":"string","name":"fileHash","type":"string"},{"internalType":"string","name":"ipfsHash","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"uniqueIds","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}]' 
// }

export function contractAddress (){
    return "0xe9239F06E6865b993036E73391F6108C9267Dc68"
}

export function contractABI(){
    return '[{"inputs":[{"internalType":"string","name":"_username","type":"string"},{"internalType":"string","name":"_fileHash","type":"string"},{"internalType":"string","name":"_ipfsHash","type":"string"},{"internalType":"string[]","name":"_viewerUsernames","type":"string[]"},{"internalType":"string[]","name":"_editorUsernames","type":"string[]"}],"name":"storeFileHashes","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_randomNumber","type":"uint256"}],"name":"storeRandomNumber","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"string","name":"_fromUsername","type":"string"},{"internalType":"string","name":"_toUsername","type":"string"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"string","name":"_username","type":"string"}],"name":"getFiles","outputs":[{"components":[{"internalType":"string","name":"fileHash","type":"string"},{"internalType":"string","name":"ipfsHash","type":"string"},{"internalType":"string[]","name":"viewerUsernames","type":"string[]"},{"internalType":"string[]","name":"editorUsernames","type":"string[]"}],"internalType":"struct FileStore.File[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"randomNumber","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}]'
}